name: Docker build check

on:
    push:
     branches:
      - master
    pull_request:
        branches:
            - master

jobs:
  docker-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - name: Docker installlation
        run: |
            sudo apt update 
            sudo apt install -y ca-certificates curl gnupgsudo install -m 0755 -d /etc/apt/keyrings
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo tee /etc/apt/keyrings/docker.asc > /dev/null
            sudo chmod a+r /etc/apt/keyrings/docker.asc
            echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
            $(. /etc/os-release && echo $VERSION_CODENAME) stable" | \
            sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt update
            sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: Docker image builds
        run: sudo docker build -t clinic-app:latest .
      
      - name: Docker image deletion
        run: sudo docker rmi clinic-app:latest
